INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (1, 'Ana', 34, 'IT', 'Reclutador', 32038, '2015-03-29', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (2, 'David', 32, 'Recursos Humanos', 'Reclutador', 45319, '2022-03-21', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (3, 'Victoria', 42, 'Ventas', 'Analista', 45932, '2015-01-27', 18625);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (4, 'Jorge', 34, 'IT', 'Analista', 35739, '2018-04-14', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (5, 'Marta', 33, 'Recursos Humanos', 'Desarrollador', 48169, '2019-04-27', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (6, 'Laura', 43, 'Marketing', 'Reclutador', 31568, '2022-04-05', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (7, 'Teresa', 43, 'Ventas', 'Desarrollador', 36194, '2016-05-25', 10571);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (8, 'Beatriz', 45, 'Marketing', 'Analista', 47198, '2017-02-26', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (9, 'Adrián', 27, 'Ventas', 'Desarrollador', 47458, '2021-11-10', 14635);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (10, 'Iván', 39, 'Recursos Humanos', 'Desarrollador', 32253, '2022-02-14', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (11, 'Silvia', 22, 'Marketing', 'Desarrollador', 48179, '2015-12-31', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (12, 'Beatriz', 42, 'IT', 'Desarrollador', 40840, '2016-09-13', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (13, 'Isabel', 22, 'Recursos Humanos', 'Desarrollador', 46394, '2020-02-10', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (14, 'Pedro', 37, 'Recursos Humanos', 'Analista', 36091, '2018-12-22', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (15, 'Gabriel', 32, 'Marketing', 'Vendedor', 48397, '2018-04-21', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (16, 'Ramiro', 29, 'Marketing', 'Reclutador', 46877, '2016-06-02', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (17, 'Diego', 39, 'Recursos Humanos', 'Analista', 48325, '2017-12-20', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (18, 'Jorge', 36, 'Marketing', 'Reclutador', 38026, '2016-04-10', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (19, 'Valeria', 42, 'Recursos Humanos', 'Desarrollador', 31366, '2022-02-10', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (20, 'Ricardo', 24, 'Recursos Humanos', 'Desarrollador', 38396, '2022-08-21', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (21, 'Alicia', 41, 'Marketing', 'Reclutador', 45005, '2015-04-09', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (22, 'Jorge', 29, 'Marketing', 'Reclutador', 31547, '2021-06-27', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (23, 'Ines', 44, 'Ventas', 'Desarrollador', 46144, '2017-07-11', 15304);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (24, 'Sofía', 25, 'IT', 'Desarrollador', 32939, '2019-08-18', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (25, 'Patricia', 40, 'Marketing', 'Analista', 43959, '2017-02-18', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (26, 'Patricia', 34, 'Marketing', 'Reclutador', 46885, '2020-12-05', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (27, 'Isabel', 40, 'Recursos Humanos', 'Vendedor', 32865, '2017-04-29', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (28, 'Ana', 37, 'IT', 'Vendedor', 41570, '2019-07-29', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (29, 'Manuel', 27, 'IT', 'Reclutador', 46687, '2022-01-24', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (30, 'Elena', 26, 'Marketing', 'Desarrollador', 46446, '2017-12-11', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (31, 'Diego', 39, 'Marketing', 'Reclutador', 30580, '2015-01-05', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (32, 'Rafael', 42, 'Ventas', 'Vendedor', 30704, '2020-01-07', 14357);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (33, 'Monica', 35, 'IT', 'Reclutador', 35089, '2021-07-17', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (34, 'Elena', 42, 'Ventas', 'Reclutador', 48553, '2017-02-04', 11173);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (35, 'Monica', 40, 'Marketing', 'Reclutador', 42638, '2020-10-01', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (36, 'Andrés', 37, 'Recursos Humanos', 'Desarrollador', 49885, '2015-10-31', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (37, 'Noelia', 32, 'Ventas', 'Reclutador', 33068, '2019-07-01', 12885);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (38, 'Diego', 45, 'IT', 'Desarrollador', 40269, '2022-03-17', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (39, 'Silvia', 31, 'IT', 'Vendedor', 47792, '2021-12-03', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (40, 'Manuel', 28, 'IT', 'Reclutador', 35076, '2018-12-23', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (41, 'Adrián', 42, 'Marketing', 'Desarrollador', 31207, '2019-02-21', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (42, 'Carlos', 37, 'Recursos Humanos', 'Desarrollador', 47371, '2017-03-15', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (43, 'Carlos', 26, 'Marketing', 'Vendedor', 33524, '2020-04-21', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (44, 'Paula', 41, 'Marketing', 'Desarrollador', 40972, '2018-05-27', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (45, 'Ines', 35, 'Recursos Humanos', 'Analista', 34547, '2015-06-11', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (46, 'Sara', 44, 'Ventas', 'Vendedor', 40212, '2017-07-16', 12887);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (47, 'Rafael', 38, 'Marketing', 'Vendedor', 31216, '2021-06-29', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (48, 'Manuel', 41, 'Marketing', 'Vendedor', 33518, '2022-08-14', NULL);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (49, 'Valeria', 41, 'Ventas', 'Desarrollador', 48795, '2021-11-23', 12337);
INSERT INTO empleados (id_empleado, nombre, edad, departamento, cargo, salario, fecha_ingreso, ventas) VALUES (50, 'Ines', 41, 'Marketing', 'Reclutador', 38975, '2020-11-17', NULL);