use tallerGrupal;
INSERT INTO libros (titulo, autor_id, año_publicacion, genero, disponibilidad) VALUES
('Sombras del Amanecer: Filosofía y Honor en la Guerra', 18, 2001, 'Filosofía', TRUE),
('Corazón en Llamas: Guía para el Perdón y la Empatía', 3, 1998, 'Autoayuda', FALSE),
('Hierro y Pasión: Supervivencia en Mundos Fríos', 25, 2005, 'Supervivencia', TRUE),
('El Misterio del Crepúsculo: Secretos del Otro Lado', 12, 2011, 'Misterio', FALSE),
('Fortalezas de Poder: Construyendo el Imperio Personal', 7, 2000, 'Liderazgo', TRUE),
('Luz y Sombra: Historia Oculta de los Reinos Perdidos', 20, 1997, 'Historia', FALSE),
('Filo y Honor: El Camino del Guerrero en Silencio', 4, 2013, 'Autoayuda', TRUE),
('Relatos del Vacío: La Paz en el Caos', 15, 2009, 'Filosofía', FALSE),
('Sueños de Héroes: Historias para un Futuro Brillante', 27, 2002, 'Ficción', TRUE),
('Más allá de las Estrellas: Reflexiones sobre la Bondad', 2, 2019, 'Reflexiones', TRUE),
('Risas Cósmicas: Manual de Travesuras Universales', 29, 2010, 'Comedia', FALSE),
('Redes y Secretos: El Arte del Tacto y la Manipulación', 9, 2003, 'Psicología', TRUE),
('Éxitos del Caballero: La Verdad sobre Mis Hazañas', 1, 2015, 'Autobiografía', FALSE),
('Bajo Tierra: La Belleza de la Vida en las Profundidades', 26, 2007, 'Naturaleza', TRUE),
('Reflejos de Lluvia: Filosofía en el Camino Errante', 11, 2008, 'Filosofía', FALSE),
('Guía Completa para la Cocina de Alta Energía', 6, 2020, 'Cocina', TRUE),
('Peregrinos del Silencio: Explorando el Mundo Interior', 22, 2016, 'Filosofía', TRUE),
('Entre las Corrientes: Historias del Viento y el Mar', 17, 1999, 'Narrativa', FALSE),
('Sueños Perpetuos: La Esencia de un Viaje Eterno', 14, 2004, 'Fantasía', TRUE),
('Brillando Siempre: Reflexiones sobre Fama y Espejismo', 8, 2012, 'Autoayuda', FALSE),
('Cuentos al Lado del Fuego: Enseñanzas del Corazón', 19, 2017, 'Religión', TRUE),
('Entre Penumbras: Elegancia en la Guerra', 10, 2006, 'Historia', FALSE),
('Rumbo al Amanecer: Aventura y Propósito en la Vida', 24, 2001, 'Aventura', TRUE),
('Lo Que Importa No Siempre Se Ve: Reflexiones del Subsuelo', 16, 2014, 'Filosofía', TRUE),
('Ensoñaciones en Neblina: Poemas de lo Efímero', 21, 2018, 'Poesía', FALSE),
('Estrella Guerrera: Batallas en lo Desconocido', 30, 1995, 'Ciencia Ficción', TRUE),
('Más Allá de la Luz: Historia y Destino de los Guardianes', 23, 2011, 'Fantasía', FALSE),
('Llamas que Cuentan: Relatos desde las Brasas', 5, 2003, 'Narrativa', TRUE),
('La Llamada de la Devoción: Caminos a la Iluminación', 28, 2007, 'Religión', FALSE),
('El Camino Oscuro: Filosofía del Olvido y la Redención', 13, 2009, 'Filosofía', TRUE);
