use tallergrupal;
INSERT INTO usuarios (nombre_usuario, tipo_usuario, email) VALUES
('Link', 'Estudiante', 'hero_of_time@gmail.com'),
('Zelda', 'Profesora', 'princess_of_zelda@yahoo.com'),
('Kirby', 'Estudiante', 'pink_ball_of_fun@hotmail.com'),
('Meta Knight', 'Profesor', 'dark_knight_rose@gmail.com'),
('Susie', 'Estudiante', 'dino_drummer@yahoo.com'),
('Ralsei', 'Profesora', 'fluffy_sorcerer@hotmail.com'),
('Knight', 'Estudiante', 'shiny_armor_fan@gmail.com'),
('Hornet', 'Profesora', 'sting_operation@yahoo.com'),
('Sans', 'Profesor', 'punny_bone_teacher@hotmail.com'),
('Papyrus', 'Estudiante', 'spaghetti_lover@gmail.com'),
('Sora', 'Estudiante', 'keyblade_master@yahoo.com'),
('Cloud Strife', 'Profesor', 'spiky_haired_hero@hotmail.com'),
('Mario', 'Estudiante', 'jumpman_mario@gmail.com'),
('Peach', 'Profesora', 'cake_baking_queen@yahoo.com'),
('Ganon', 'Profesor', 'dark_lord_of_gloom@hotmail.com'),
('Waddle Dee', 'Estudiante', 'waddle_all_day@gmail.com'),
('Hollow Knight', 'Estudiante', 'silent_but_deadly@yahoo.com'),
('Quirrel', 'Profesor', 'spider_teacher@hotmail.com'),
('Chara', 'Profesora', 'determined_soul@gmail.com'),
('Frisk', 'Estudiante', 'determined_player@yahoo.com'),
('Pikachu', 'Estudiante', 'electric_cutie@hotmail.com'),
('Samus Aran', 'Profesora', 'bounty_hunter_babe@gmail.com'),
('Yoshi', 'Estudiante', 'dino_friend@yahoo.com'),
('Luigi', 'Estudiante', 'green_mustache@hotmail.com'),
('Marin', 'Profesora', 'ocean_heroine@gmail.com'),
('Demi-fiend', 'Profesor', 'demon_king_of_cool@yahoo.com'),
('Krystal', 'Profesora', 'fox_with_a_plan@hotmail.com'),
('Mewtwo', 'Estudiante', 'psychic_poke_guru@gmail.com'),
('Fox McCloud', 'Estudiante', 'space_pilot_fox@yahoo.com'),
('Donkey Kong', 'Profesor', 'banana_king@hotmail.com');
